version: '3.8'

services:
  db:
      image: postgres:15-alpine
      restart: unless-stopped
      container_name: wagtail-db
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - 5433:5432
      env_file:
        - ./.env
      networks:
        - epr-hub-net

  wagtail:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wagtail
    volumes:
      - media:/app/media
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    ports:
      - 8000:8000
    # command : wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - epr-hub-net

  

networks:
  epr-hub-net:

volumes:
  postgres_data:
  media: