# Generated by Django 4.1.7 on 2023-04-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
