# Generated by Django 4.1.7 on 2023-04-09 11:05

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_homepage_options_homepage_banner_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="platforms",
            field=wagtail.fields.StreamField(
                [
                    (
                        "epr_component",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "heading",
                                        wagtail.blocks.CharBlock(
                                            form_classname="title"
                                        ),
                                    ),
                                    ("paragraph", wagtail.blocks.RichTextBlock()),
                                    (
                                        "image",
                                        wagtail.images.blocks.ImageChooserBlock(),
                                    ),
                                    (
                                        "button_page",
                                        wagtail.blocks.PageChooserBlock(required=False),
                                    ),
                                    (
                                        "button_url",
                                        wagtail.blocks.URLBlock(
                                            help_text="If the button page above is selected, that will be used first.",
                                            required=False,
                                        ),
                                    ),
                                ]
                            )
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
