# Generated by Django 4.1.7 on 2023-04-09 12:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0005_alter_homepage_platforms"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content_list",
                    wagtail.fields.StreamField(
                        [
                            (
                                "content",
                                wagtail.blocks.ListBlock(
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "heading",
                                                wagtail.blocks.CharBlock(
                                                    form_classname="title"
                                                ),
                                            ),
                                            (
                                                "paragraph",
                                                wagtail.blocks.RichTextBlock(),
                                            ),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(),
                                            ),
                                            (
                                                "button_page",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "button_url",
                                                wagtail.blocks.URLBlock(
                                                    help_text="If the button page above is selected, that will be used first.",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                    icon="clipboard-list",
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="platforms",
            field=wagtail.fields.StreamField(
                [
                    (
                        "epr_component",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "heading",
                                        wagtail.blocks.CharBlock(
                                            form_classname="title"
                                        ),
                                    ),
                                    ("paragraph", wagtail.blocks.RichTextBlock()),
                                    (
                                        "image",
                                        wagtail.images.blocks.ImageChooserBlock(),
                                    ),
                                    (
                                        "button_page",
                                        wagtail.blocks.PageChooserBlock(required=False),
                                    ),
                                    (
                                        "button_url",
                                        wagtail.blocks.URLBlock(
                                            help_text="If the button page above is selected, that will be used first.",
                                            required=False,
                                        ),
                                    ),
                                ]
                            ),
                            icon="globe",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
